spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:application-${spring.profiles.active}.yml
  profiles:
    active: prod

fastapi:
  server:
    url: https://port-0-workermanagers-ai-m9i2iiuc1e546d59.sel4.cloudtype.app  # FastAPI 서버 주소

server:
  connection-timeout: 300000  # 5분
  servlet:
    session:
      timeout: 30m   # 세션 타임아웃 (30분)
  tomcat:
    connection-timeout: 300000  # 5분
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
  forward-headers-strategy: native
